web_app:
  name: "bulebell"
  mode: "dev"
  port: 8080
log: 
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "mysql"
  max_open_conns: 100
  max_idle_conns: 1000

redis:
  host: "127.0.0.1"
  port: 16379
  user: "root"
  password: ""
  db: 0
  pool_size: 100

  

